//
//  File.swift
//  
//
//  Created by Laurent B on 31/05/2020.
//

import Foundation

public let descriptionForChallenge29 = """
\nProject Euler: Problem 29: Distinct powers:
\n
Consider all integer combinations of ab for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5:

If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:

4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125

How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ n and 2 ≤ b ≤ n?

https://projecteuler.net/problem=29/n
https://www.freecodecamp.org/learn/coding-interview-prep/project-euler/problem-29-distinct-powers
"""
